CREATE SCHEMA to_do_list;

USE to_do_list;

CREATE TABLE `todo` (
`id` int NOT NULL AUTO_INCREMENT,
`item` VARCHAR(255) NOT NULL,
`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`id`)
);

